version: '3.8'

services:
  app:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_laravel_app
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - app-network
    command: >
      /bin/sh -c "
        php artisan migrate --force &&
        if [ ! -f /var/www/storage/seeds_done ]; then
          php artisan db:seed --force &&
          touch /var/www/storage/seeds_done;
        fi;
        php-fpm
      "

  webserver:
    image: nginx:alpine
    container_name: my_nginx_server
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
